### ISSUE TITLE
Creación de Menú

### ISSUE THREAD

**Issue by JuanManuelEsquivel** [cualtos-industry-introduction/Equipo2H2CSM#3]
---Descripción---
Mostrar un menú con las siguientes opciones:
Agregar contacto
Mostrar contactos agregados
Consulta por contacto
Actualizar contactos
Eliminar contactos

**Comment by cislast** [comment]
Horacio se encarga de programar el menú.
Juan Manuel se encarga de programar agregar contacto
Claudia se encarga de programar mostrar contactos agregados
Héctor se encarga de programar la consulta por contacto
Sergio se encarga de programar la actualización de contactos
César se encarga de programar eliminar contactos

**Comment by cislast** [comment]
Tarea realizada
